services:
  - type: web
    name: zeus-iot
    env: node
    buildCommand: "cd server && npm install && npx prisma generate && npx prisma db push"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
